### ISSUE TITLE
Enable Fail2Ban jail from bash Script

### ISSUE THREAD

**Issue by TurtleWolf** [TurtleWolf/docker-run-it-ubuntu-bin-bash#10]
I'm [Automating Initial Server Setup with Ubuntu 18.04](https://www.digitalocean.com/community/tutorials/automating-initial-server-setup-with-ubuntu-18-04) on Digital Ocean using the user-data insert to start a new server.
I've got it to install `Fail2Ban`, but now I need to add the jails, starting with `[sshd]`
which is just a matter of adding `enabled = true`

I've recently learned `echo` would append to the end of the file,
or I could use `sed` to edit an existing line..
But how would I add a new line in between existing lines, when there's nothing to be replaced?
### starting sample
```
#
# JAILS
#

#
# SSH servers
#

[sshd]

# To use more aggressive sshd modes set filter parameter "mode" in jail.local:
# normal (default), ddos, extra or aggressive (combines all).
# See "tests/files/logs/sshd" or "filter.d/sshd.conf" for usage example and details.
#mode   = normal
port    = ssh
logpath = %(sshd_log)s
backend = %(sshd_backend)s


[dropbear]

port     = ssh
logpath  = %(dropbear_log)s
backend  = %(dropbear_backend)s


[selinux-ssh]

port     = ssh
logpath  = %(auditd_log)s


#
# HTTP servers
#
```
### I need to add `enabled = true` below the line starting with `backend` and above the stanza for `[dropbear]`
```
backend = %(sshd_backend)s
enabled = true

[dropbear]
```

**Comment by TurtleWolf** [comment]
`sed -i "s/logpath = %(sshd_log)s/logpath = %(sshd_log)s\nenabled = true/" /etc/fail2ban/jail.local`

**Comment by navotera** [comment]
Thank you this really help us 👍

**Comment by TurtleWolfe** [comment]
Glad to hear it, sometimes I feel like I'm just echoing in the wind..
